services:
  springboot-hrms:
    container_name: springboot-hrms
    image: springboot-hrms:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-hrms:3306/hrmsdb
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
    depends_on:
      - mysql-hrms
    networks:
      - hrms-network

  mysql-hrms:
    container_name: mysql-hrms
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: hrmsdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"
    networks:
      - hrms-network

networks:
  hrms-network:
    driver: bridge
