name: Deploy to Dev Server

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USERNAME }}
          key: ${{ secrets.EC2_DEV_SSH_KEY }}
          script: |
            # git pull이 안전 모드 오류 발생하지 않도록
            git config --global --add safe.directory /home/ec2-user/back

            # 프로젝트 디렉토리 이동
            cd /home/ec2-user/back

            # 최신 코드 가져오기
            git pull origin develop

            # 도커 중지 (없어도 실행되게 || true 적용)
            docker-compose down || true

            # 도커 다시 빌드 + 실행
            docker-compose up -d --build
